version: "3.8"
services:
  go-server:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true 
    ports:
      - 3000:3000
    command: sleep infinity
    volumes:
      - .:/home/test-user/workspace
